//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYBUSINESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductionOrder()
        {
            this.ProductionOrderDetails = new HashSet<ProductionOrderDetail>();
        }
    
        public string Id { get; set; }
        public Nullable<decimal> SOSerial { get; set; }
        public decimal BillAmount { get; set; }
        public double BillPaid { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<double> PrevBalance { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> SaleReturn { get; set; }
        public Nullable<decimal> SODId { get; set; }
        public Nullable<double> SaleOrderAmount { get; set; }
        public Nullable<double> SaleReturnAmount { get; set; }
        public Nullable<int> SaleOrderQty { get; set; }
        public Nullable<int> SaleReturnQty { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public string Remarks { get; set; }
        public string ProductionOrderName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ProductionOrderQty { get; set; }
        public Nullable<decimal> EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionOrderDetail> ProductionOrderDetails { get; set; }
    }
}
