//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYBUSINESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyBalanceVnd
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> ClosingBalance { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<decimal> UserId { get; set; }
        public string OpeningCurrencyDetail { get; set; }
        public string ClosingCurrencyDetail { get; set; }
    }
}
