//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYBUSINESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public decimal Id { get; set; }
        public string RentId { get; set; }
        public Nullable<decimal> ProductId { get; set; }
        public Nullable<System.DateTime> RentStartDate { get; set; }
        public Nullable<System.DateTime> RentEndDate { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Rent Rent { get; set; }
    }
}
